sudo: false
language: node_js
node_js:
  - 12
cache: 
  directories:
    - node_modules

before_install:
  - npm install hexo-cli -g

install:
  - npm install
  - npm install hexo-deployer-git --save
  - git clone https://github.com/theme-next/hexo-theme-next themes/next
  
branches:
  only:
    - sourcefile # build master branch only
script:
  - hexo clean
  - hexo generate # generate static files
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  target_branch: master
  on:
    branch: sourcefile
  local-dir: public